### ISSUE TITLE
skin with capitalized letter will be dropped after a little

### ISSUE THREAD

**Issue by xion87** [Th3Tr0LLeR/SkinsRestorer---Maro#69]
I got exact the same issue reported on forum
"For some reason all player names in cache.yml has all letters in lower case. And changed skins with /sr set command are always drops after reload bungeecord (or after some amount of time) because of this. Skins don't drops when using player and skin names with ALL letters in specific cases.
For example:
-set skin name umbie to player with name SELLER works well
-skin name baebar to player with name govard works well
-but set skin name Pioner (1 different case) to player with name alexgrist drops after some time
same thing with skin name klawneed to player with name Sovushka"

**Comment by Platinteufel** [comment]
I've got the same problem. Yesterday I've set my skin with /skin set Paluten and today it has been dropped and updated to my normal skin.

**Comment by Th3Tr0LLeR** [comment]
I will put some tag on the skins set by /skin set, so they will never expire :)

**Comment by Platinteufel** [comment]
Thanks! :) But why does it depend on the case sensitivity? It worked well in previous versions.^^

**Comment by Platinteufel** [comment]
Could you push a hotfix for this please? :/

**Comment by Th3Tr0LLeR** [comment]
Seems nothing is wrong for me.. lel :D

**Comment by Platinteufel** [comment]
Try /skin set Paluten .. it will drop after 1-2 days and you will get back your own skin.

**Comment by xion87** [comment]
there are also some user thare are crashing with skinrestorer, i will report a ticket later

**Comment by Platinteufel** [comment]
Please fix this, it's very annoying. :/

**Comment by Augustin37** [comment]
I got the same problem :/

**Comment by Platinteufel** [comment]
bumb

**Comment by Platinteufel** [comment]
@Th3Tr0LLeR please D:

**Comment by Platinteufel** [comment]
My custom skins reset every day .. it's so annoying D:

**Comment by xion87** [comment]
i think he will dont fix until one of us donate him for that, he replying in his topic of his 0.10 cent Ultimate one of chamber....

**Comment by Platinteufel** [comment]
Don't think that's the point. But if there's an easy fix (tag on custom skins), push it for us please. :(

**Comment by Blackfire62** [comment]
Fixed in next version.

**Comment by xion87** [comment]
You fixed also the crash issue?

**Comment by Augustin37** [comment]
thank you! :D

**Comment by Platinteufel** [comment]
@Blackfire62 When can we expect the release on spigotmc?

**Comment by Blackfire62** [comment]
@xion87 I didnt experience any crashes during my testing with both mysql and file database, so I guess.

@Platinteufel depends on Troller, I dont have the rights for the project on SpigotMc site

**Comment by xion87** [comment]
@Blackfire62 
https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/75
https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/72

**Comment by Blackfire62** [comment]
Well, If its incompatibile with ViaVersion, ill try it out tomorrow. If I get any errors, ill try to fix them, but so far, nothing.

**Comment by xion87** [comment]
Is not a viaversion issue, some data is not saved correct on database yml and it cause random crashes with players, or they can't enter, happen it with my every day and i have to reset the skinsrestorer database for fix it

**Comment by Blackfire62** [comment]
Theres no way corrupted data could be acquired with MojangAPI (you wouldnt see skins) . 
Only reason I can think of is the yaml that could possibly do something with it.

Well, if you experience anything, report it with debug txt file (in new version its /sr debug command ) and we can figure out something.

**Comment by xion87** [comment]
i will wait new version and try to debug it :)

**Comment by xion87** [comment]
Somesone Can compile the source and share here? Most my user are start to get angry about this

**Comment by Blackfire62** [comment]
You can try out my latest compiled version on my Fork here:
https://github.com/Blackfire62/SkinsRestorer---Maro/


(Direct link : https://github.com/Blackfire62/SkinsRestorer---Maro/raw/master/SkinsRestorer-11.7-Alpha.jar )

**Comment by Augustin37** [comment]
Thank you for the build Blackfire! :D
I made a clean sql DB but I get crashed when I enter the game, and I get an error on the console too

Console error:
```java
[12:58:06] [Thread-48/WARN]: Exception in thread "Thread-48"
[12:58:06] [Thread-48/WARN]: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
[12:58:06] [Thread-48/WARN]: 	at skinsrestorer.bukkit.UniversalSkinFactory.updateSkin(UniversalSkinFactory.java:314)
[12:58:06] [Thread-48/WARN]: 	at skinsrestorer.bukkit.UniversalSkinFactory$1.applySkin(UniversalSkinFactory.java:56)
[12:58:06] [Thread-48/WARN]: 	at skinsrestorer.shared.format.SkinProfile.applySkin(SkinProfile.java:65)
[12:58:06] [Thread-48/WARN]: 	at skinsrestorer.bukkit.UniversalSkinFactory.applySkin(UniversalSkinFactory.java:34)
[12:58:06] [Thread-48/WARN]: 	at skinsrestorer.shared.api.SkinsRestorerAPI.applySkin(SkinsRestorerAPI.java:83)
[12:58:06] [Thread-48/WARN]: 	at skinsrestorer.bukkit.listeners.LoginListener$2.run(LoginListener.java:88)
[12:58:06] [Thread-48/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

Client crash:
![Client crash](http://image.noelshack.com/fichiers/2016/22/1465039027-2016-06-04-12-58-37b.png)

**Comment by Platinteufel** [comment]
It's expecting getOnlinePlayers() to return a Player[], instead this was dropped in CB 1.9 to return a Collection<? extends Player>.

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Bukkit.html#getOnlinePlayers%28%29

**Comment by Blackfire62** [comment]
Wait why it looks for a Player array one? 
I was 100% sure that my current bukkit lib for compiling has the <? extends Playter> , Ive been using it since 1.8 (it wanst dropped just with 1.9) .
Whatever, I will renew my libraries when I get some time and recompile.

**Comment by Blackfire62** [comment]
Just updated it, use the same link.

**Comment by Augustin37** [comment]
The error message is gone, but the client is still crashing when connecting:

when a player is connecting :
```java
[00:55:04] [User Authenticator #4/INFO]: UUID of player zatrios is 20267c13-401f-3703-befe-be7bf66f741d
[00:55:04] [Netty Epoll Server IO #2/ERROR]: java.lang.NullPointerException
[00:55:04] [Netty Epoll Server IO #1/ERROR]: java.lang.NullPointerException
[00:55:04] [Netty Epoll Server IO #1/ERROR]: java.lang.NullPointerException
[00:55:04] [Server thread/INFO]: zatrios[/92.152.136.161:55566] logged in with entity id 5583 at ([IronWorld]12800.315001202282, 93.0, 1917.8665911943372)
```
and the same client crash error from before

**Comment by Platinteufel** [comment]
As soon as mcapi is used for getting the players skin, it will only recieve a steve skin. I'm using your alpha version.

**Comment by Platinteufel** [comment]
Just tested it with an older version (11.2), mcapi works perfectly there, so any recent change must have broke it.

**Comment by Platinteufel** [comment]
Edit: Also doesn't work in 11.6. 11.2 is fine though.

**Comment by Blackfire62** [comment]
Yeah, my patterns for mcapi are broken, i just saw the skin data that it saves.

That error doesnt quit give me enough info. Are you using latwsr verison? Did you do /sr debug ? Version of server and client? Anything other i should know?
Did you try removing all plugins except SR and then applying?

**Comment by xion87** [comment]
i downgraded to 11.6 as planteufel, working perfect

**Comment by xion87** [comment]
@Blackfire62  the error is the same of the issue that i linked, it spam these errors also at hub
https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/75
https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/72

Also the errors spam and random crash are bugs introduced with yml format for storage

**Comment by Blackfire62** [comment]
These errors and crashes might be caused by the corrupted data saved in players properies from McAPI, eh, well, I already fixed it.

Finishing few things and I will make an update.

**Comment by Platinteufel** [comment]
The client crashes also happen for me in your alpha version, same error like in the screen above.

**Comment by Platinteufel** [comment]
There is a npe almost on every player join, and some players can't connect.

**Comment by Platinteufel** [comment]
mcapi also doesn't work in 11.6, but there are no client errors

**Comment by Blackfire62** [comment]
New update, try this one out , should have fixed https://github.com/Blackfire62/SkinsRestorer---Maro/raw/master/SkinsRestorer-11.7-Alpha.jar

**Comment by Platinteufel** [comment]
Hey @Blackfire62,
thanks, but I got still an issue: If a player joins that don't have any premium account (I've just tested Tesgewshgg) ^^ he can't join the server and get this message:

![unbenannt](https://cloud.githubusercontent.com/assets/13700636/15805669/93ac2024-2b31-11e6-9109-6a9b0f5b6e8b.png)

In console you can only see "java.lang.NullPointerException".

**Comment by Augustin37** [comment]
Thanks for the update, same problem with offline players :/
I did the /sr debug, I don't know if this could help
```yml
Java version: 1.8.0_91
Bukkit version: git-Paper-763 (MC: 1.9.4)
SkinsRestoerer version: 11.7

Plugin list: CleanroomGenerator (1.0.0), SupplySign (1.9.8), RemoteToolkitPlugin (R10_A15.3), Blood (1.3.2), Antibots (1.21), TuxTwoLib (1.9-b7), LWCTweaks (3.3.0), NametagEdit (4.0.2), SkinsRestorer (11.7), ArmedArmorStands (1.1.1), VoxelSniper (5.171.0-SNAPSHOT), ViaVersion (0.8.4), IPLog (1.1), TimeLock (0.5), CoreProtect (2.12.0), dynmap (2.3-SNAPSHOT-1137), WorldEdit (6.1.3-SNAPSHOT;3552-edb4c0b), TimTheEnchanter (3.0), Spawn_Bed (0.1), HealthBar (1.8.3), Replicator (0.2.0), SHSM (0.1.1), MultiInv (3.3.6), ClearLag (2.9.1), ChatControl (5.3.2), Chairs (4.8), WorldBorder (1.8.5), Modifyworld (1.19.7), EasyEnchant (1.2.2c), ProtocolLib (4.0.1), NoCheatPlus (3.14.0-SNAPSHOT-sMD5NET-b984), Stables (1.9.10.6), NoFloatingTrees (0.12.1), SignEdit (3.3.10), PermissionsEx (1.23.4), CommandDelayer (1.0), StaffChat (2.0), Vault (1.5.6-b49), LWC (4.5.0-SNAPSHOT), WorldGuard (6.1.2-SNAPSHOT;1664-5bd2125 with custom flags plugin.), World_Portal (0.2.7.1), WeatherMan (1.0.3), ChatManager (1.19.1), JSONAPI (5.7.0), Orebfuscator4 (4.0.14-SNAPSHOT), Essentials (TeamCity), MailBox (2.7), PlotMe (0.16.3), Jobs (3.3.7), TreasureChest (8.4.9), Citizens (2.0.18-SNAPSHOT (build 1369)), WGRegionEvents (1.1), PluginsBaker (0.3), WGCustomFlags (1.9), FriendlyHopper (0.1.2), PlotMe-DefaultGenerator (0.16.1), WGKeepInventoryFlags (0.3.1), Sentry (1.9.1), WGRegionCommands (0.1), DynmapPlotMe (0.3), EssentialsSpawn (TeamCity), TitleManager (1.5.11), Dynmap-WorldGuard (0.80), Multiverse-Core (2.5.0-SNAPSHOT-b722), WGRegionEffects (1.4), AuthMe (5.2-SNAPSHOT-b1082), ShowCaseStandalone (770), HolographicDisplays (2.1.13), RegionSelfService (2.0.2-HB-b14), SignShop (2.11.0Dev), IslandWorld (6.8), Multiverse-NetherPortals (2.5.0-SNAPSHOT-b712), 

Property output from MojangAPI (Notch) : 
Name: textures
Value: eyJ0aW1lc3RhbXAiOjE0NjUxMzMzMTY3MDgsInByb2ZpbGVJZCI6IjA2OWE3OWY0NDRlOTQ3MjZhNWJlZmNhOTBlMzhhYWY1IiwicHJvZmlsZU5hbWUiOiJOb3RjaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTExNmU2OWE4NDVlMjI3ZjdjYTFmZGRlOGMzNTdjOGM4MjFlYmQ0YmE2MTkzODJlYTRhMWY4N2Q0YWU5NCJ9LCJDQVBFIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWVjM2NhYmZhZWVkNWRhZmU2MWM2NTQ2Mjk3ZTg1M2E1NDdjMzllYzIzOGQ3YzQ0YmY0ZWI0YTQ5ZGMxZjJjMCJ9fX0=
Signature: YkF1vZGz2RM4Bvjfsl48O+brtWQT4pCanGe09kfDWeddu+0Eyp4Nzd3uVUA2VAn1vIc+RU2b0jvAn9EI8LGW7q3iMBX8XKsQiTSAGyGuJzGtwOJvmvZ3H+eP2Sn76u29TbbUfMJo7rBvM9YpAtpKyz0vJFofncfKSDUj80cdTWBxK91GUCjgphTeSQz5+KpQdj1N3D2Dp4A4K4BUoxFSIQcOe/d7wfsjiN3ZBcDRs2eRS2+KM00qNSNwLUTGPXlCHyXbZv3tRKlggDcbi9NQx250vZB1VJi60vXfIn5gi2MLes9DUOD1oZr1jzPA5eiHi4VKoI5v/5emANPn9hOuZRnQ/vCkeP2vpsFXoWYtcU8qd2aNRezK39p9qzqyxyDfEEPwbvfm86ZjvcYA+3eKSOpvDzWAEpKQLQJQRsa3nlEa2UCZmaKmCPppkrWSNxz0EFFiS321MNZYUxQyqQpMPYZo0SKJGenMaf+ZvlQzRpcNeQ7cLnkznjRit4eJZw5pBmI68pnFIQE5c52vYNvp0vQBvXHLnuGp8nXY+sK3zih4pXG3Filq3bXU8++OEm0QAb6whbe6r5D3d0U449OfWrcfQNi/Qj6j5p5DAcYGuzwesICrXrmg2jRb7DwwfEfu09XsuFlpHuA/nlQkfDXn2GmyQgLbTUJKaCTV7qqBUbA=

Raw data from MojangAPI (Blackfire62): 
{"id":"616bed1293744cafbd12e201f6b43ca9","name":"Blackfire62","properties":[{"signature":"tUGZ9z9E3bBf+lH9RpSyz7QVhC4FsAhzgIo4Zf262fFZkHfm4Ip2ynmHgA77dwW7PtEFsO78bBFJ6BNKs5vtW5f88TBAON4MBG6bhAMX3o7QmnYzP+9exb4N6A75GF6K78Fd1XW2AXANT+qjU4mdfTq8wZPjUaHWs5R1mgTBVKpleMGVmMB5Ubcn9kDfD/S8A3rPB/ZjN0Tq//BL+gHyWnTaTf2bw5RjeGb8dyfneTzi+yVvpDTdb675FUxB1UTyZRCROsj6h+6neWZ0zMZ3CBoEkgYXnOD0HVEnHKsHX7qysGw3++Oc5QXWb3gt29H5Bw1eld3II2XHOpvAQfzB2VFc/RdEHY1cFqd1Jgr7ohHGWKzGvYF5KQBhTYBo3T7ovsMko7iaAke0QvkJsxXeGvRo1jIKhQeZYwxWgHQywP0jrfIoMuJBbksW/Zm+EnBJE8F4CvlIBQED2rrCUt37lQsV952Fq/Ax9ALkeUUV2IghLITAQAy32COi99KZ+kEBy1ZtensmEOJx5htcdgZcwxNk+nN71C9pcVcCrUlzJZGrn9ElRfMxYJ935VQDBosG6F0coBojmtI3n7yL8NZi+/++MOiw+PbQJkUef9MuCTauTW44bAJ8ac6K6M4Jk1vDB85lg8T1XucKhQwMOLLeXdUSszqOvyt4/tL+se3dAjQ=","name":"textures","value":"eyJ0aW1lc3RhbXAiOjE0NjUxMzMzMTcwMjQsInByb2ZpbGVJZCI6IjYxNmJlZDEyOTM3NDRjYWZiZDEyZTIwMWY2YjQzY2E5IiwicHJvZmlsZU5hbWUiOiJCbGFja2ZpcmU2MiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzZiOWM3MTJjN2YyMDE5Mjk2YjY2OGJkY2E4YzlmMjNjYjZlNTNmMTI0NTMzMWUzYmEwZWJjMzg3OTA3NDY5In19fQ=="}]}
```

**Comment by Blackfire62** [comment]
Should be fixed: https://github.com/Blackfire62/SkinsRestorer---Maro/raw/master/SkinsRestorer-11.7-Alpha.jar

**Comment by Platinteufel** [comment]
Seems to be fixed, thanks! Would sqlite be faster than storing skins in yml?

**Comment by Platinteufel** [comment]
And does anyone have an idea why the instant skin updating works on my testserver, but not on my main server?

**Comment by Platinteufel** [comment]
Just tested a little bit: After removing the playerdata folder from my world instant skin updating works again, but that can't be the solution for me. :(

**Comment by Augustin37** [comment]
Same problem for me, instant skin don't work, also when a player connects, I got this message:
```java
[Ljava.lang.Object;@16d429d2
```
And also when I do /sr drop playername, my character is duplicated, and when I log out/log in, my skin isn't dropped

![dupli](http://image.noelshack.com/fichiers/2016/22/1465148090-2016-06-05-19-29-04.png)

A player tell me that he didn't see his own skin (he was transparent)
![transp](http://image.noelshack.com/fichiers/2016/22/1465148526-2016-06-05-19-27-18.png)

**Comment by Blackfire62** [comment]
That might be broken packets and the message after connecting was intedned for my debugging, i just didnt remove it.  

ill try to fix it.

**Comment by Augustin37** [comment]
Okay thank you very much :D

**Comment by Platinteufel** [comment]
I'm just wondering why this is related to the playerdata in the world folder.

**Comment by Blackfire62** [comment]
Theres no way it can be related to playerdata, its strange.

**Comment by xion87** [comment]
you cant just drop all work and start the work to 11.6? is the best version, and dont have any issue, because with the new yml storage started the issues (corrupted players, crash at hub, skin dropped, ecc)

**Comment by Augustin37** [comment]
I aggree 11.2 or 11.0-v2 was a great version, after that, problems started, like some skins did not show (#71, #60) etc.

**Comment by Blackfire62** [comment]
Youre talking yaml (which shouldnt be a problem, we use custom yaml class DataFiles, instead of YamlConfiguration . If it would do problems I could remake it, but so far none ) . 

Some skindata were corrupted because of McAPI output change, which is now fixed. (Thats why some skins didnt work) 

Also im pretty sure its not related to playerdata in any way, no skin data or anything we use is saved or get from there while sending packets for skin changing.

I also reworked the way skins and player data are stored, so no problems should appear here too.

**Comment by Platinteufel** [comment]
Well, the instant skin updating doesn't work on my main server. I will try to reproduce it soon. Could you give me a version with some debug checks on this side?

**Comment by Blackfire62** [comment]
Try /sr debug , I might improve the debug thingy to show off even more info, just in case. 
So far it shows, like, your version, plugins, example saved skin data (to see if its corrupted) and raw output from mojangapi.

**Comment by Platinteufel** [comment]
/sr debug: http://pastebin.com/UE7kbGSq

I'm not kiddin, after deleting the playerdata folder of my world it works again ..

**Comment by Platinteufel** [comment]
And after testing the instant skin updating for a while I'm there two times after /skin set
Dude, I'm sorry to say, but the skin updating is still buggy in your version.

![skins](https://cloud.githubusercontent.com/assets/13700636/15862961/a1346bec-2cd1-11e6-9de7-a47fb486189b.png)

**Comment by Platinteufel** [comment]
-.- .. IM SO DUMB. Yes, it is related to playerdata .. but not directly. 
I've compared two player datas for about 30 minutes .. and now I got it. I'm so dumb ..

The skin didn't update because of the diamond sword in my hand. Please take a look at this:
https://youtu.be/Q8XKokwxtXE

Maybe because there could be items in both hands since 1.9? Dunno.

**Comment by Blackfire62** [comment]
I see, I see, I got that in my seting aswell. Thats something wrong with packets.

**Comment by Platinteufel** [comment]
My players also reported that the skins are still resetting after 1-2 days. :/

**Comment by Blackfire62** [comment]
Hm, I might remove the automatic cache cleaner, since an update gets triggered whenever player joins, there is no need to clean the cache. 

Also your clone on bukkit servers is caused by not removing the player before adding it again properly. Since Ive done it all in reflection, it may take me a little bit of time to fix it (and considering the fact I barely got any time at all)

**Comment by Platinteufel** [comment]
No problem, should I create a seperate ticket for all the issues in this one?

**Comment by Blackfire62** [comment]
If you want to, you can create a new one and group in all the known issues and vids/pics about them.

But only those which hasnt been fixed yet.
It would be easier for me.
